[account_voucher_common] 8.0.7.3.2
open-synergy/opnsynid-account-voucher pull request #98
Opened 2021-06-14 05:03 UTC by mikevhe18

2021-06-15 08:57 UTC, andhit-r requested changes

2021-06-15 08:57 UTC, andhit-r commented on account_voucher_common/views/account_voucher_common_views.xml
> +                        <label for="name" />
Mike ini ga perlu, nanti labelnya ada 2 donk

2021-06-15 08:57 UTC, andhit-r commented on account_voucher_common/__openerp__.py
> +    "version": "8.0.7.3.2",
Naik nya digit kedua dr kiri krn butuh update

2021-06-15 10:04 UTC, mikevhe18 commented on account_voucher_common/views/account_voucher_common_views.xml
> +                        <label for="name" />
mas udah coba install ??
soalnya modul yg lain itu inherit ke views ini, dimana xpath ke display name, makanya harus ditambahkan kalau ngga semua error

2021-06-21 14:35 UTC, andhit-r requested changes

2021-06-21 14:35 UTC, andhit-r commented on account_voucher_common/views/account_voucher_common_views.xml
> +                        <label for="name" />
Berarti gunakan <label for="display_name">. Bagian ini ga ada masalah. Baris 133 dan 134 yang harus ada koreksi. Dan koreksi yang lo lakukaan sdh benar

2021-06-22 06:56 UTC, merged